repos:
  - repo: local
    hooks:
      - id: run-unittest
        name: Run unittests
        entry: python -m unittest discover -s tests -v  
        language: system
        types: [python]
        pass_filenames: false
